const $=s=>document.querySelector(s),os=$('#os'),wins=$('#windows');let z=10,bootTimer;
const apps={
 about:{name:'About Me',icon:'N',color:'#c2a4ff',html:`<h2>김현민</h2><p class="lead">다양한 웹사이트를 탐구하고 분석하며, 사용자에게 좋은 경험을 제공하는 UI를 설계하는 김현민입니다.</p><div class="id-card"><div class="avatar">N</div><div><b>Frontend Developer · UX/UI Designer</b><p>이메일: hfjevblkjfk@gmail.com<br>GitHub: github.com/nalak1206<br>Notion: 준비 중</p></div></div><h3>자기소개</h3><p class="lead">다양한 기업과 서비스의 웹사이트를 살펴보며, 어떤 UI가 사용자에게 좋은 인상을 주고 편리한 경험을 제공하는지 분석하는 것을 좋아합니다.</p><p class="lead">새로운 아이디어가 떠오르면 단순히 생각으로 끝내지 않고, 직접 디자인하거나 개발하면서 실제 결과물로 만들어 봅니다. 구현 과정에서 아직 익숙하지 않은 기술이 필요할 때는 AI를 활용해 해결 방법을 탐색하고, 내용을 이해한 뒤 프로젝트에 적용하고 있습니다.</p><p class="lead">앞으로 디자인과 개발 역량을 함께 발전시켜, 보기 좋을 뿐만 아니라 누구나 쉽고 편리하게 사용할 수 있는 웹 서비스를 만드는 것이 목표입니다.</p>`},
 projects:{name:'Projects',icon:'✦',color:'#ffbd70',html:`<h2>Selected Projects</h2><p class="lead">카드를 선택하면 프로젝트 상세 정보를 확인할 수 있습니다.</p><div class="card-grid">${[['Major 팀 프로젝트','음악 소통 및 공유 서비스','Figma · Team · 2026.04.23 — 06.10'],['Discord 자동 메시지 봇','정해진 시간에 메시지를 전송하는 Python Bot','Python · launchd'],['React · Supabase 게시판','작성·수정과 데이터베이스 연동 경험','React · Vite · Supabase'],['LoL RP 계산기','필요한 RP 구매 조합을 계산하는 반응형 도구','HTML · CSS · JavaScript']].map((x,i)=>`<article class="card project" data-project="${i}"><small>0${i+1} / ${x[2]}</small><b>${x[0]}</b><p>${x[1]}</p><span>상세 보기 ↗</span></article>`).join('')}</div>`},
 skills:{name:'Skills',icon:'⌘',color:'#7fe0c1',html:`<h2>Skills & Experience</h2><p class="lead">숙련도를 숫자로 단정하지 않고, 실제 적용 경험을 중심으로 정리합니다.</p><h3>실제 사용 가능 <span class="tag">READY</span></h3><div class="card-grid"><article class="card"><b>Python</b><p>디스코드 자동 메시지 봇 제작에 사용했습니다. 정해진 시간에 메시지와 이미지를 전송하고, macOS의 <code>launchd</code>로 봇 자동 실행을 설정했습니다.</p></article><article class="card"><b>HTML</b><p>LoL RP 계산기 같은 웹사이트의 제목, 입력창, 버튼, 결과 영역 등 기본 구조를 직접 구성할 수 있습니다.</p></article><article class="card"><b>CSS</b><p>색상·여백·정렬·버튼·입력창 UI를 디자인합니다. Flexbox를 활용한 요소 배치와 기본 반응형 화면 구성이 가능합니다.</p></article></div><h3>학습 중 <span class="tag">LEARNING</span></h3><div class="card-grid"><article class="card"><b>JavaScript</b><p>입력값에 따른 계산과 버튼 클릭 기반 화면 변화를 학습 중입니다. LoL RP 계산기에서 입력값 검증과 결과 출력을 구현했습니다.</p></article><article class="card"><b>React</b><p>컴포넌트로 화면을 분리·재사용하는 방법을 학습합니다. React Router로 게시글 목록, 작성, 수정 페이지를 구분한 게시판을 제작했습니다.</p></article><article class="card"><b>Supabase</b><p>React 프로젝트의 게시글 데이터를 저장·조회·등록·수정하기 위해 데이터베이스 연결과 클라이언트 설정을 학습하고 있습니다.</p></article></div>`},
 log:{name:'Dev Log',icon:'≡',color:'#9db4ff',html:`<h2>Dev Log</h2><p class="lead">배운 내용과 문제 해결 과정을 기록합니다.</p>${['Supabase export 오류 해결','macOS에서 Python 파일 실행 권한 문제 해결','Discord Bot 자동 실행 설정','React Router를 이용한 게시판 페이지 분리','Figma 팀 프로젝트 화면 구조 설계','LoL RP 계산기 입력 UI 개선'].map((t,i)=>`<article class="log"><small>${['Troubleshooting','Python','Automation','React','Figma','JavaScript'][i]} · 2026</small><b>${t}</b><p>문제를 확인하고 원인을 분리해 해결한 과정을 정리했습니다.</p></article>`).join('')}`},
 timeline:{name:'Timeline',icon:'↗',color:'#ff9ec8',html:`<h2>Learning Timeline</h2><div class="timeline">${[['2025','프론트엔드 분야에 관심을 갖고 학습 시작'],['2025','Python과 HTML · CSS · JavaScript 학습'],['2026','Figma 팀 프로젝트 · Discord Bot 개발'],['2026','React · Supabase 게시판 프로젝트'],['NEXT','사용자 중심의 제품을 만드는 개발자']].map(x=>`<article><small>${x[0]}</small><b>${x[1]}</b></article>`).join('')}</div>`},
 gallery:{name:'Gallery',icon:'▦',color:'#ffb0d4',html:`<h2>Major · Gallery</h2><p class="lead">음악 소통 및 공유 사이트의 기획·프로토타입 결과물입니다.</p><div class="image-grid"><figure><img src="assets/major-cover.png" alt="Major 프로젝트 표지 디자인"><figcaption>Major · project cover</figcaption></figure><figure><img src="assets/major-screens.png" alt="Major 음악 서비스 주요 모바일 화면"><figcaption>주요 모바일 화면</figcaption></figure><figure><img src="assets/major-features.png" alt="Major 서비스 주요 기능 소개"><figcaption>서비스 주요 기능</figcaption></figure><figure><img src="assets/major-problem.png" alt="Major 프로젝트 문제 정의"><figcaption>문제 정의와 해결 방향</figcaption></figure></div>`},
 resume:{name:'Resume',icon:'▤',color:'#e3e8f4',html:`<h2>Resume</h2><p class="lead">김현민 · Frontend Developer in Progress</p><h3>핵심 기술</h3><p>HTML · CSS · JavaScript · React · Python · Figma · Supabase</p><h3>프로젝트</h3><p>Figma 팀 프로젝트 / Discord Bot / React · Supabase 게시판 / LoL RP 계산기</p><button class="primary unavailable">이력서 PDF · 준비 중</button>`},
 contact:{name:'Contact',icon:'@',color:'#ffd67b',html:`<h2>Let's talk.</h2><p class="lead">현재 문의 기능은 준비 중입니다. 이메일 또는 GitHub를 통해 연락해 주세요.</p><h3>hfjevblkjfk@gmail.com</h3><a class="primary" href="mailto:hfjevblkjfk@gmail.com">이메일 보내기 ↗</a><a class="primary" href="https://github.com/nalak1206" target="_blank" rel="noreferrer">GitHub 열기 ↗</a><p class="lead">Notion · 준비 중</p>`},
 terminal:{name:'Terminal',icon:'›_',color:'#d1f28b',html:`<div class="terminal"><p>HYUNMIN Terminal v1.0</p><p>Type <b>help</b> to see available commands.</p><div class="term-output"></div><form class="term-form"><span>hyunmin:~$</span><input autocomplete="off" autofocus></form></div>`},
 settings:{name:'Settings',icon:'⚙',color:'#b9a9ff',html:`<h2>Settings</h2><p class="lead">HYUNMIN의 모양과 동작을 조정합니다.</p><div class="settings"><label>화이트 모드 <input class="theme-toggle" type="checkbox"></label><label>애니메이션 효과 <input class="motion" type="checkbox" checked></label><label>배경 효과 <input class="effects" type="checkbox" checked></label><label>부팅 화면 다시 보기 <button class="reboot">REBOOT</button></label></div>`}
};
function time(){let d=new Date(),t=d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),date=d.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}).toUpperCase();$('#lock-time').textContent=t;$('#tray-time').textContent=t;$('#menu-time').textContent=t;$('#lock-date').textContent=date}time();setInterval(time,30000);
function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
function renderIcons(){let list=Object.entries(apps);$('#icons').innerHTML=list.map(([id,a])=>`<button class="desk-icon" data-app="${id}"><span class="app-icon" style="background:${a.color}">${a.icon}</span>${a.name}</button>`).join('');$('#dock-apps').innerHTML=list.filter(([id])=>['about','projects','skills','log','gallery','terminal'].includes(id)).map(([id,a])=>`<button class="dock-app" data-app="${id}" title="${a.name}"><span class="app-icon">${a.icon}</span></button>`).join('');$('#start-apps').innerHTML=list.filter(([id])=>['about','projects','skills','log','contact','settings'].includes(id)).map(([id,a])=>`<button data-app="${id}">${a.icon}　${a.name}</button>`).join('')}
function openApp(id){let old=$(`.window[data-id="${id}"]`);if(old){old.style.display='block';focus(old);return}let a=apps[id],w=document.createElement('section');w.className='window active';w.dataset.id=id;w.style.left=(220+Math.random()*120)+'px';w.style.top=(85+Math.random()*80)+'px';w.innerHTML=`<header class="titlebar"><span class="win-dot" style="background:${a.color}">${a.icon}</span><b class="win-title">${a.name}</b><div class="win-controls"><button class="min">−</button><button class="max">□</button><button class="close">×</button></div></header><div class="window-content">${a.html}</div>`;wins.append(w);focus(w);bindWindow(w);toast(`${a.name} 앱을 열었습니다.`)}
function focus(w){w.classList.add('active');w.style.zIndex=++z}function bindWindow(w){w.addEventListener('pointerdown',()=>focus(w));let bar=w.querySelector('.titlebar'),drag;bar.onpointerdown=e=>{if(e.target.closest('button'))return;drag={x:e.clientX-w.offsetLeft,y:e.clientY-w.offsetTop};bar.setPointerCapture(e.pointerId)};bar.onpointermove=e=>{if(drag&&innerWidth>700){w.style.left=Math.max(0,e.clientX-drag.x)+'px';w.style.top=Math.max(0,e.clientY-drag.y)+'px'}};bar.onpointerup=()=>drag=null;w.querySelector('.close').onclick=()=>w.remove();w.querySelector('.min').onclick=()=>{w.style.display='none';addTask(w)};w.querySelector('.max').onclick=()=>w.classList.toggle('maximized');w.querySelectorAll('.project').forEach(p=>p.onclick=()=>openDetail(+p.dataset.project));let f=w.querySelector('.term-form');if(f)f.onsubmit=e=>{e.preventDefault();term(f)};w.querySelector('.motion')?.addEventListener('change',e=>document.documentElement.style.setProperty('--motion',e.target.checked?'1':'0'));w.querySelector('.effects')?.addEventListener('change',e=>$('#desktop').classList.toggle('no-effects',!e.target.checked));w.querySelector('.reboot')?.addEventListener('click',startBoot)}
function addTask(w){let b=document.createElement('button');b.className='task-item';b.textContent=apps[w.dataset.id].name;b.onclick=()=>{w.style.display='block';b.remove();focus(w)};$('#task-apps').append(b)}
function openDetail(i){let names=['Major 팀 프로젝트','Discord 자동 메시지 봇','React · Supabase 게시판','LoL RP 계산기'],major=`<h2>Major</h2><p class="lead">사용자가 음악을 감상하고, 자신만의 플레이리스트를 만들며 다른 사용자와 음악을 공유할 수 있는 음악 소통 및 공유 서비스입니다.</p><img class="project-visual" src="assets/major-cover.png" alt="Major 음악 소통 및 공유 사이트 표지"><h3>프로젝트 정보</h3><p class="lead">진행 기간: 2026년 4월 23일 — 6월 10일<br>프로젝트 형태: 팀 프로젝트<br>담당 역할: UI·UX 디자인 및 인터랙티브 프로토타입 제작</p><span class="tag">Figma</span><h3>주요 기능</h3><span class="tag">음악 스트리밍</span><span class="tag">플레이리스트 생성·관리</span><span class="tag">음악 공유</span><span class="tag">다이렉트 메시지</span><span class="tag">음악 검색·탐색</span><span class="tag">사용자 프로필</span><span class="tag">추천 음악·플레이리스트</span><h3>어려웠던 점</h3><p class="lead">음악 스트리밍, 플레이리스트, 음악 공유, 메시지 등 다양한 기능을 한 화면에 배치하면서도 사용자가 복잡함을 느끼지 않도록 UI를 구성하는 일이 가장 어려웠습니다. 각 기능을 어디에 배치해야 자연스럽게 이용할 수 있을지 많은 고민이 필요했습니다.</p><h3>해결 과정</h3><p class="lead">팀원들과 지속적으로 의견을 나누고, 실제 음악 스트리밍 서비스와 여러 유명 웹사이트의 화면 구성 및 사용자 흐름을 분석했습니다. 이를 그대로 따라 하기보다 필요한 기능과 사용자의 이동 흐름에 맞게 다시 정리했고, 주요 기능은 쉽게 발견할 수 있는 위치에 배치하며 정보 중요도에 따라 화면의 크기와 구조를 다르게 설계했습니다.</p><h3>프로젝트 결과</h3><p class="lead">완성된 디자인과 프로토타입으로 발표 대회에 참가했으며, 사용자 편의성과 디자인 완성도를 인정받아 <b>1등을 수상했습니다.</b></p><h3>배운 점</h3><p class="lead">UI 디자인은 화면을 보기 좋게 꾸미는 것을 넘어, 사용자가 서비스를 어떤 순서로 이용하고 어디에서 어려움을 느낄지를 고민하는 과정이라는 점을 배웠습니다. 또한 팀원들과 의견을 조율하고 다양한 참고 사례를 분석하는 과정이 더 좋은 결과물을 만드는 데 중요하다는 것을 경험했습니다.</p><button class="primary unavailable">프로젝트 링크 · 준비 중</button>`,a={name:names[i],icon:'□',color:'#ffbd70',html:i===0?major:`<h2>${names[i]}</h2><p class="lead">프로젝트 개요와 구현 경험을 정리한 상세 화면입니다.</p><h3>프로젝트 목적 · 역할</h3><p class="lead">사용자가 직접 사용할 수 있는 기능을 설계하고 구현했습니다. 요구사항을 화면 구조로 정리하고, 발생한 문제를 확인해 해결했습니다.</p><h3>사용 기술</h3><span class="tag">${['Figma','Python','React · Supabase','JavaScript'][i]}</span><h3>배운 점</h3><p class="lead">기능을 작은 단위로 나누고, 사용자 흐름을 기준으로 화면을 구성하는 경험을 쌓았습니다.</p><button class="primary unavailable">GitHub 링크 · 준비 중</button>`};apps.detail=a;openApp('detail')}
function term(f){let inp=f.querySelector('input'),out=f.parentElement.querySelector('.term-output'),cmd=inp.value.trim().toLowerCase();let ans={help:'help, about, projects, skills, contact, clear, whoami, date',whoami:'김현민\nFrontend Developer in Progress',about:'사용자 중심의 화면을 만드는 프론트엔드 개발자를 목표로 합니다.',projects:'Figma 팀 프로젝트\nDiscord 자동 메시지 봇\nReact · Supabase 게시판\nLoL RP 계산기',skills:'HTML, CSS, JavaScript, React, Python, Figma, Supabase',contact:'hello@example.com',date:new Date().toString()};if(cmd==='clear')out.innerHTML='';else if(ans[cmd])out.innerHTML+=`<p>khm@os:~$ ${cmd}\n${ans[cmd]}</p>`;else out.innerHTML+=`<p>command not found: ${cmd}</p>`;inp.value='';f.parentElement.scrollTop=f.parentElement.scrollHeight}
function startBoot(){os.className='booting';$('#boot-lines').innerHTML='';$('.progress i').style.width='0';let ls=['Initializing HYUNMIN OS...','Loading developer profile...','Connecting project database...','Loading skills and experiences...','System ready.'];ls.forEach((x,i)=>setTimeout(()=>$('#boot-lines').innerHTML+=`<p>› ${x}</p>`,i*420));setTimeout(()=>$('.progress i').style.width='100%',30);clearTimeout(bootTimer);bootTimer=setTimeout(()=>os.className='locked',2500)}function unlock(){os.className='ready';toast('HYUNMIN OS에 오신 것을 환영합니다. Projects에서 작업을 확인해 보세요.');openApp('projects')}$('.skip').onclick=()=>os.className='locked';$('.unlock').onclick=unlock;document.addEventListener('keydown',e=>{if(e.key==='Enter'&&os.classList.contains('locked'))unlock();if(e.key==='Escape'){$('.start-menu').classList.remove('open')}});document.addEventListener('click',e=>{let app=e.target.closest('[data-app]');if(app)openApp(app.dataset.app)});$('#start').onclick=()=>$('.start-menu').classList.toggle('open');$('.lock-action').onclick=()=>{os.className='locked';$('.start-menu').classList.remove('open')};renderIcons();startBoot();
if(localStorage.getItem('hyunmin-theme')==='light')document.body.classList.add('light');
document.addEventListener('change',event=>{if(!event.target.matches('.theme-toggle'))return;const apply=()=>{document.body.classList.toggle('light',event.target.checked);localStorage.setItem('hyunmin-theme',event.target.checked?'light':'dark')};if(document.startViewTransition)document.startViewTransition(apply);else apply();toast(event.target.checked?'화이트 모드를 적용했습니다.':'다크 모드를 적용했습니다.')});
document.addEventListener('click',event=>{if(!event.target.closest('[data-app="settings"]'))return;setTimeout(()=>{const toggle=document.querySelector('.theme-toggle');if(toggle)toggle.checked=document.body.classList.contains('light')})});
function openApp(id){let old=$(`.window[data-id="${id}"]`);if(old){old.style.display='flex';old.classList.remove('minimizing');old.classList.add('launching');setTimeout(()=>old.classList.remove('launching'),650);focus(old);return}let a=apps[id],w=document.createElement('section');w.className='window active launching';w.dataset.id=id;w.style.left=(220+Math.random()*120)+'px';w.style.top=(85+Math.random()*80)+'px';w.innerHTML=`<header class="titlebar"><span class="win-dot" style="background:${a.color}">${a.icon}</span><b class="win-title">${a.name}</b><div class="win-controls"><button class="min">−</button><button class="max">□</button><button class="close">×</button></div></header><div class="window-content">${a.html}</div>`;wins.append(w);focus(w);bindWindow(w);setTimeout(()=>w.classList.remove('launching'),650);toast(`${a.name} 앱을 열었습니다.`)}
function closeWindow(w){w.classList.add('closing');setTimeout(()=>w.remove(),520)}
function bindWindow(w){w.addEventListener('pointerdown',()=>focus(w));let bar=w.querySelector('.titlebar'),drag;bar.onpointerdown=e=>{if(e.target.closest('button'))return;drag={x:e.clientX-w.offsetLeft,y:e.clientY-w.offsetTop};bar.setPointerCapture(e.pointerId)};bar.onpointermove=e=>{if(drag&&innerWidth>700){w.style.left=Math.max(0,e.clientX-drag.x)+'px';w.style.top=Math.max(0,e.clientY-drag.y)+'px'}};bar.onpointerup=()=>drag=null;w.querySelector('.close').onclick=()=>closeWindow(w);w.querySelector('.min').onclick=()=>{w.classList.add('minimizing');setTimeout(()=>{w.style.display='none';w.classList.remove('minimizing');addTask(w)},500)};w.querySelector('.max').onclick=()=>w.classList.toggle('maximized');w.querySelectorAll('.project').forEach(p=>p.onclick=()=>openDetail(+p.dataset.project));let f=w.querySelector('.term-form');if(f)f.onsubmit=e=>{e.preventDefault();term(f)};w.querySelector('.motion')?.addEventListener('change',e=>document.documentElement.style.setProperty('--motion',e.target.checked?'1':'0'));w.querySelector('.effects')?.addEventListener('change',e=>$('#desktop').classList.toggle('no-effects',!e.target.checked));w.querySelector('.reboot')?.addEventListener('click',startBoot)}
function addTask(w){let b=document.createElement('button');b.className='task-item';b.textContent=apps[w.dataset.id].name;b.onclick=()=>{w.style.display='flex';w.classList.add('launching');setTimeout(()=>w.classList.remove('launching'),650);b.remove();focus(w)};$('#task-apps').append(b)}
document.addEventListener('change',event=>{if(event.target.matches('.motion'))document.documentElement.classList.toggle('motion-off',!event.target.checked);if(event.target.matches('.effects'))$('#desktop').classList.toggle('no-effects',!event.target.checked)});
function openApp(id){let old=$(`.window[data-id="${id}"]`);if(old){document.querySelectorAll('.window').forEach(w=>{if(w!==old)w.remove()});$('#task-apps').innerHTML='';old.style.display='flex';old.classList.remove('minimizing');old.classList.add('launching');setTimeout(()=>old.classList.remove('launching'),650);focus(old);return}document.querySelectorAll('.window').forEach(w=>w.remove());$('#task-apps').innerHTML='';let a=apps[id],w=document.createElement('section');w.className='window active launching';w.dataset.id=id;w.style.left=(220+Math.random()*120)+'px';w.style.top=(85+Math.random()*80)+'px';w.innerHTML=`<header class="titlebar"><span class="win-dot" style="background:${a.color}">${a.icon}</span><b class="win-title">${a.name}</b><div class="win-controls"><button class="min">−</button><button class="max">□</button><button class="close">×</button></div></header><div class="window-content">${a.html}</div>`;wins.append(w);focus(w);bindWindow(w);setTimeout(()=>w.classList.remove('launching'),650);toast(`${a.name} 앱을 열었습니다.`)}
function bindWindow(w){w.addEventListener('pointerdown',()=>focus(w));let bar=w.querySelector('.titlebar'),drag;bar.onpointerdown=e=>{if(e.target.closest('button'))return;drag={x:e.clientX-w.offsetLeft,y:e.clientY-w.offsetTop};bar.setPointerCapture(e.pointerId)};bar.onpointermove=e=>{if(drag&&innerWidth>700){w.style.left=Math.max(0,e.clientX-drag.x)+'px';w.style.top=Math.max(0,e.clientY-drag.y)+'px'}};bar.onpointerup=()=>drag=null;w.querySelector('.close').onclick=()=>closeWindow(w);w.querySelector('.min').onclick=()=>{w.classList.add('minimizing');setTimeout(()=>w.remove(),500)};w.querySelector('.max').onclick=()=>w.classList.toggle('maximized');w.querySelectorAll('.project').forEach(p=>p.onclick=()=>openDetail(+p.dataset.project));let f=w.querySelector('.term-form');if(f)f.onsubmit=e=>{e.preventDefault();term(f)};w.querySelector('.motion')?.addEventListener('change',e=>document.documentElement.style.setProperty('--motion',e.target.checked?'1':'0'));w.querySelector('.effects')?.addEventListener('change',e=>$('#desktop').classList.toggle('no-effects',!e.target.checked));w.querySelector('.reboot')?.addEventListener('click',startBoot)}
function syncDock(){document.querySelectorAll('.dock-app,.quick-app').forEach(button=>button.classList.toggle('is-running',!!document.querySelector(`.window[data-id="${button.dataset.app}"]`)))}
function openApp(id){let old=$(`.window[data-id="${id}"]`);if(old){old.style.display='flex';old.classList.remove('minimizing');old.classList.add('launching');setTimeout(()=>old.classList.remove('launching'),650);focus(old);syncDock();return}let a=apps[id],w=document.createElement('section');w.className='window active launching';w.dataset.id=id;w.style.left=(220+Math.random()*120)+'px';w.style.top=(85+Math.random()*80)+'px';w.innerHTML=`<header class="titlebar"><span class="win-dot" style="background:${a.color}">${a.icon}</span><b class="win-title">${a.name}</b><div class="win-controls"><button class="min">−</button><button class="max">□</button><button class="close">×</button></div></header><div class="window-content">${a.html}</div>`;wins.append(w);focus(w);bindWindow(w);setTimeout(()=>w.classList.remove('launching'),650);syncDock();toast(`${a.name} 앱을 열었습니다.`)}
function closeWindow(w){w.classList.add('closing');setTimeout(()=>{w.remove();syncDock()},520)}
function bindWindow(w){w.addEventListener('pointerdown',()=>focus(w));let bar=w.querySelector('.titlebar'),drag;bar.onpointerdown=e=>{if(e.target.closest('button'))return;drag={x:e.clientX-w.offsetLeft,y:e.clientY-w.offsetTop};bar.setPointerCapture(e.pointerId)};bar.onpointermove=e=>{if(drag&&innerWidth>700){w.style.left=Math.max(0,e.clientX-drag.x)+'px';w.style.top=Math.max(0,e.clientY-drag.y)+'px'}};bar.onpointerup=()=>drag=null;w.querySelector('.close').onclick=()=>closeWindow(w);w.querySelector('.min').onclick=()=>{w.classList.add('minimizing');setTimeout(()=>{w.style.display='none';w.classList.remove('minimizing');syncDock()},500)};w.querySelector('.max').onclick=()=>w.classList.toggle('maximized');w.querySelectorAll('.project').forEach(p=>p.onclick=()=>openDetail(+p.dataset.project));let f=w.querySelector('.term-form');if(f)f.onsubmit=e=>{e.preventDefault();term(f)};w.querySelector('.motion')?.addEventListener('change',e=>document.documentElement.style.setProperty('--motion',e.target.checked?'1':'0'));w.querySelector('.effects')?.addEventListener('change',e=>$('#desktop').classList.toggle('no-effects',!e.target.checked));w.querySelector('.reboot')?.addEventListener('click',startBoot)}
function openApp(id){let old=$(`.window[data-id="${id}"]`);if(old){old.style.display='flex';old.classList.remove('minimizing');old.classList.add('launching');setTimeout(()=>old.classList.remove('launching'),650);focus(old);syncDock();return}let a=apps[id],w=document.createElement('section');w.className='window active launching';w.dataset.id=id;w.style.left=Math.max(30,Math.round((innerWidth-690)/2+(Math.random()*48-24)))+'px';w.style.top=Math.max(48,Math.round((innerHeight-680)/2+(Math.random()*38-19)))+'px';w.innerHTML=`<header class="titlebar"><span class="win-dot" style="background:${a.color}">${a.icon}</span><b class="win-title">${a.name}</b><div class="win-controls"><button class="min">−</button><button class="max">□</button><button class="close">×</button></div></header><div class="window-content">${a.html}</div>`;wins.append(w);focus(w);bindWindow(w);setTimeout(()=>w.classList.remove('launching'),650);syncDock();toast(`${a.name} 앱을 열었습니다.`)}
function renderIcons(){let list=Object.entries(apps);$('#icons').innerHTML=list.map(([id,a])=>`<button class="desk-icon" data-app="${id}"><span class="app-icon" style="background:${a.color}">${a.icon}</span>${a.name}</button>`).join('');$('#dock-apps').innerHTML=list.filter(([id])=>['about','projects','skills','log','gallery','terminal'].includes(id)).map(([id,a])=>`<button class="dock-app" data-app="${id}" title="${a.name}"><span class="app-icon">${a.icon}<i class="running-dot" aria-hidden="true"></i></span></button>`).join('');$('#start-apps').innerHTML=list.filter(([id])=>['about','projects','skills','log','contact','settings'].includes(id)).map(([id,a])=>`<button data-app="${id}">${a.icon}　${a.name}</button>`).join('')}
/* HYUNMIN 브랜드 표기 통일 */
function term(f){let inp=f.querySelector('input'),out=f.parentElement.querySelector('.term-output'),cmd=inp.value.trim().toLowerCase();let ans={help:'help, about, projects, skills, contact, clear, whoami, date',whoami:'김현민\nFrontend Developer in Progress',about:'사용자 중심의 화면을 만드는 프론트엔드 개발자를 목표로 합니다.',projects:'Figma 팀 프로젝트\nDiscord 자동 메시지 봇\nReact · Supabase 게시판\nLoL RP 계산기',skills:'HTML, CSS, JavaScript, React, Python, Figma, Supabase',contact:'hello@example.com',date:new Date().toString()};if(cmd==='clear')out.innerHTML='';else if(ans[cmd])out.innerHTML+='<p>hyunmin:~$ '+cmd+'\n'+ans[cmd]+'</p>';else out.innerHTML+='<p>command not found: '+cmd+'</p>';inp.value='';f.parentElement.scrollTop=f.parentElement.scrollHeight}
function startBoot(){os.className='booting';$('#boot-lines').innerHTML='';$('.progress i').style.width='0';let ls=['Initializing HYUNMIN...','Loading developer profile...','Connecting project database...','Loading skills and experiences...','System ready.'];ls.forEach((x,i)=>setTimeout(()=>$('#boot-lines').innerHTML+='<p>› '+x+'</p>',i*420));setTimeout(()=>$('.progress i').style.width='100%',30);clearTimeout(bootTimer);bootTimer=setTimeout(()=>os.className='locked',2500)}
function unlock(){os.className='ready';toast('HYUNMIN에 오신 것을 환영합니다. Projects에서 작업을 확인해 보세요.');openApp('projects')}
$('.unlock').onclick=unlock;
function minimizeDockWindow(windowElement){if(windowElement.classList.contains('minimizing')||windowElement.classList.contains('closing'))return;windowElement.classList.add('minimizing');setTimeout(()=>{if(!windowElement.isConnected)return;windowElement.style.display='none';windowElement.classList.remove('minimizing');syncDock()},500)}
function toggleDockWindow(id){let windowElement=$(`.window[data-id="${id}"]`);if(windowElement&&getComputedStyle(windowElement).display!=='none'){minimizeDockWindow(windowElement);return}openApp(id)}
document.querySelectorAll('.dock-app,.quick-app').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();toggleDockWindow(button.dataset.app)}));
function activateApplication(id){let windowElement=$(`.window[data-id="${id}"]`);if(!windowElement){openApp(id);return}if(windowElement.classList.contains('closing'))return;if(getComputedStyle(windowElement).display==='none'){windowElement.style.display='flex';windowElement.classList.remove('minimizing');windowElement.classList.add('launching');setTimeout(()=>windowElement.classList.remove('launching'),650)}focus(windowElement);syncDock()}
document.querySelectorAll('#icons [data-app],#start-apps [data-app]').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();$('.start-menu').classList.remove('open');activateApplication(button.dataset.app)}));
function toast(msg){if(String(msg).includes('앱을 열었습니다.'))return;let notice=$('#toast');notice.textContent=msg;notice.classList.add('show');setTimeout(()=>notice.classList.remove('show'),3500)}
function unlock(){os.className='ready';toast('HYUNMIN에 오신 것을 환영합니다. About Me에서 기본 소개를 확인해 보세요.');openApp('about')}
$('.unlock').onclick=unlock;
